cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'caskroom/cask'

# base
brew 'ssh-copy-id'
brew 'openssl'
brew 'gcc'
brew 'git'
brew 'wget'
brew 'trash'
brew 'mas'
cask 'google-chrome'

cask '1password'
cask 'cleanmymac'
mas 'The Unarchiver', id: 425424353

# productive
cask 'iterm2'
cask 'alfred'
mas 'Dash', id: 449589707
brew 'zsh'
brew 'macvim', args: ['with-override-system-vim']
brew 'tmux'
brew 'autojump'
brew 'tree'

brew 'diff-so-fancy'
brew 'fabric'
# brew 'ack'
brew 'the_silver_searcher'
cask 'sublime-text'
mas 'Patterns', id: 429449079

# proxy
cask 'shadowsocksx'
brew 'polipo'
cask 'vyprvpn'

# vm
cask 'docker'
cask 'parallels-desktop'

# programming
brew 'python'
brew 'python3'
brew 'go'
brew 'maven'
brew 'scala', args: ['with-docs']
brew 'sbt'
brew 'zinc'
brew 'nvm'
cask 'java'

# client
brew 'httpie'
brew 'mycli'
brew 'zookeeper'
cask 'postgres'
cask 'mongohub'

# document
brew 'pandoc'
brew 'ffmpeg'
brew 'gifsicle'
cask 'mou'

# note
mas 'Quiver', id: 866773894

# time and plan 
mas 'OmniFocus', id: 867299399
mas 'Pomodoro Time', id: 973134470

# reading
mas 'Reeder', id: 880001334

# communication
mas 'WeChat', id: 836500024
# mas 'Unibox', id: 702816521

# os tools
cask 'unetbootin'

# servers
brew 'mysql'
brew 'nginx'
brew 'elasticsearch'
brew 'varnish'
brew 'postgresql'
brew 'redis'
brew 'memcached'
brew 'mongodb'
