os: osx
osx_image: xcode8.2
script:
  - cp -r $TRAVIS_BUILD_DIR $HOME/
  - sh ~/dotfiles/travis_install_app.sh
  - sh ~/dotfiles/install_dotfile.sh
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
      - mainliufeng:l4gnbJ5TxgrehTWhmI907mFo#github
    on_success: change
    on_failure: always
