#!/usr/bin/env python

import os
import fire

import inquirer
from importlib.machinery import SourceFileLoader


dotfiles_path = os.path.join(os.environ['HOME'], 'dotfiles')
common_setup_path = os.path.join(dotfiles_path, 'common', 'setup.py')
setup = SourceFileLoader('setup', common_setup_path).load_module()


def setup_config_path(app):
    return os.path.join(dotfiles_path, app, 'setup.yaml')


def find_apps():
    apps = []
    for app in os.listdir(dotfiles_path):
        if os.path.isfile(setup_config_path(app)):
            apps.append(app)
    return apps


def check_apps(apps):
    questions = [
        inquirer.Checkbox(
            'apps',
            message="Select which to install",
            choices=apps
        ),
    ]
    return inquirer.prompt(questions)['apps']


def main(app=None):
    if app:
        apps = [app]
        need_confirm = True
    else:
        apps = find_apps()
        apps = check_apps(apps)
        need_confirm = False

    for app in apps:
        config_path = setup_config_path(app)
        setup.install_by_config(config_path, need_confirm)

if __name__ == '__main__':
    fire.Fire(main)
