#!/usr/bin/env python

import os
import sys

from importlib.machinery import SourceFileLoader

dotfiles_path = os.path.join(os.environ['HOME'], 'dotfiles')
common_setup_path = os.path.join(dotfiles_path, 'common', 'setup.py')
setup = SourceFileLoader('setup', common_setup_path).load_module()


def select_apps(apps):
    inquirer_path = os.path.join(dotfiles_path, 'external', 'inquirer', 'inquirer', '__init__.py')
    inquirer = SourceFileLoader('inquirer', inquirer_path).load_module()

    questions = [
        inquirer.Checkbox(
            'apps',
            message="Select which to install",
            choices=apps
        ),
    ]
    return inquirer.prompt(questions)['apps']


def main():
    if len(sys.argv) > 1:
        app = sys.argv[1]
    else:
        app = None

    if app:
        apps = [app]
        need_confirm = True
    else:
        apps = setup.list_apps()
        apps = select_apps(apps)
        need_confirm = False

    for app in apps:
        setup.install_app(app, need_confirm=need_confirm)

if __name__ == '__main__':
    main()
