-- Generated from the existing config and its sources. Original files are preserved.
hl.config({["xwayland.force_zero_scaling"]=true,["input.kb_layout"]="us",["input.kb_variant"]="",["input.kb_model"]="",["input.kb_options"]="ctrl:nocaps",["input.kb_rules"]="",["input.follow_mouse"]=1,["input.touchpad.disable_while_typing"]=true,["input.touchpad.natural_scroll"]=true,["input.touchpad.tap_to_click"]=true,["input.sensitivity"]=0,["gestures.workspace_swipe_distance"]=100,["gestures.workspace_swipe_invert"]=true,["general.gaps_in"]=5,["general.gaps_out"]=5,["general.border_size"]=4,["general.col.active_border"]={["colors"]={"rgba(33ccffee)","rgba(00ff99ee)"},["angle"]=45.0},["general.col.inactive_border"]="rgba(444444cc)",["general.layout"]="master",["decoration.rounding"]=1,["decoration.blur.enabled"]=false,["decoration.blur.size"]=4,["decoration.blur.passes"]=4,["decoration.blur.new_optimizations"]=true,["decoration.shadow.range"]=4,["decoration.shadow.render_power"]=3,["decoration.shadow.color"]="rgba(1a1a1aee)",["group.col.border_active"]="rgba(00c8ffff)",["group.col.border_inactive"]="rgba(2b3b4acc)",["group.col.border_locked_active"]="rgba(ff8a00ff)",["group.col.border_locked_inactive"]="rgba(5a2f00cc)",["group.groupbar.height"]=20,["group.groupbar.font_size"]=11,["group.groupbar.font_weight_active"]="bold",["group.groupbar.font_weight_inactive"]="normal",["group.groupbar.gradients"]=true,["group.groupbar.text_color"]="rgba(ffffffff)",["group.groupbar.text_color_inactive"]="rgba(c0c0c0ff)",["group.groupbar.text_color_locked_active"]="rgba(ffffffff)",["group.groupbar.text_color_locked_inactive"]="rgba(ffddbbff)",["group.groupbar.indicator_height"]=4,["group.groupbar.col.active"]="rgba(2b8cffff)",["group.groupbar.col.inactive"]="rgba(1f232aff)",["group.groupbar.col.locked_active"]="rgba(ff8a00ff)",["group.groupbar.col.locked_inactive"]="rgba(5a2f00ff)",["animations.enabled"]=true,["dwindle.preserve_split"]=true,["master.new_status"]="master",["binds.scroll_event_delay"]=10})
hl.curve("myBezier",{["type"]="bezier",["points"]={{0.1,0.9},{0.1,1.05}}})
hl.animation({["leaf"]="windows",["enabled"]=true,["speed"]=2.0,["bezier"]="myBezier",["style"]="slide"})
hl.animation({["leaf"]="windowsOut",["enabled"]=true,["speed"]=2.0,["bezier"]="myBezier",["style"]="slide"})
hl.animation({["leaf"]="border",["enabled"]=true,["speed"]=2.0,["bezier"]="default"})
hl.animation({["leaf"]="borderangle",["enabled"]=true,["speed"]=2.0,["bezier"]="default"})
hl.animation({["leaf"]="fade",["enabled"]=true,["speed"]=2.0,["bezier"]="default"})
hl.animation({["leaf"]="workspaces",["enabled"]=true,["speed"]=2.0,["bezier"]="default"})
hl.animation({["leaf"]="specialWorkspace",["enabled"]=true,["speed"]=2.0,["bezier"]="myBezier",["style"]="slidevert top"})
hl.animation({["leaf"]="specialWorkspaceIn",["enabled"]=true,["speed"]=2.0,["bezier"]="myBezier",["style"]="slidevert top"})
hl.animation({["leaf"]="specialWorkspaceOut",["enabled"]=true,["speed"]=2.0,["bezier"]="myBezier",["style"]="slidevert top"})
hl.monitor({["output"]="",["mode"]="highres",["position"]="auto",["scale"]=2})
-- Keep Super+1 through Super+0 on the laptop; private agent outputs start at 11.
for workspace = 1, 10 do
  hl.workspace_rule({workspace=tostring(workspace),monitor="eDP-1"})
end
hl.env("XCURSOR_SIZE","16")
hl.env("GTK_IM_MODULE","fcitx")
hl.env("QT_IM_MODULE","fcitx")
hl.env("XMODIFIERS","@im=fcitx")
hl.env("GDK_SCALE","1")
hl.env("CHROME_EXTRA_ARGS","--force-device-scale-factor=1.0")
hl.layer_rule({["name"]="native-migrated-7",["match"]={["namespace"]="^(lockscreen|hyprlock)$"},["blur"]=true})
hl.window_rule({["name"]="native-migrated-8",["match"]={["class"]="^(wofi)$"},["animation"]="slide"})
hl.window_rule({["name"]="native-migrated-9",["match"]={["class"]="^(confirmo)$"},["float"]=true})
hl.window_rule({["name"]="native-migrated-10",["match"]={["class"]="^(confirmo)$"},["pin"]=true})
hl.window_rule({["name"]="native-migrated-11",["match"]={["title"]="^AGENT\\.md$"},["float"]=true})
hl.window_rule({["name"]="native-migrated-12",["match"]={["title"]="^AGENT\\.md$"},["center"]=true})
hl.window_rule({["name"]="native-migrated-13",["match"]={["title"]="^Code Agents Config$"},["float"]=true})
hl.window_rule({["name"]="native-migrated-14",["match"]={["title"]="^Code Agents Config$"},["center"]=true})
hl.window_rule({["name"]="native-migrated-15",["match"]={["class"]="^(ChatGPT)$"},["float"]=true})
hl.window_rule({["name"]="native-migrated-16",["match"]={["class"]="^(ChatGPT)$"},["center"]=true})
hl.window_rule({["name"]="native-migrated-17",["match"]={["class"]="^(ChatGPT)$"},["no_initial_focus"]=true})
hl.window_rule({["name"]="native-migrated-18",["match"]={["class"]="^(xwaylandvideobridge)$"},["opacity"]="0.0 override"})
hl.window_rule({["name"]="native-migrated-19",["match"]={["class"]="^(xwaylandvideobridge)$"},["no_anim"]=true})
hl.window_rule({["name"]="native-migrated-20",["match"]={["class"]="^(xwaylandvideobridge)$"},["no_initial_focus"]=true})
hl.window_rule({["name"]="native-migrated-21",["match"]={["class"]="^(xwaylandvideobridge)$"},["max_size"]="1 1"})
hl.window_rule({["name"]="native-migrated-22",["match"]={["class"]="^(xwaylandvideobridge)$"},["no_blur"]=true})
hl.window_rule({["name"]="native-migrated-23",["match"]={["class"]="^com.alibabainc.dingtalk$",["title"]="^钉钉$"},["size"]="1522 916"})
hl.window_rule({["name"]="native-migrated-24",["match"]={["class"]="^com.alibabainc.dingtalk$",["title"]="^钉钉$"},["max_size"]="1522 916"})
hl.window_rule({["name"]="native-migrated-25",["match"]={["class"]="^com.alibabainc.dingtalk$",["title"]="^钉钉$"},["center"]=true})
hl.gesture({["fingers"]=4,["direction"]="swipe",["action"]="workspace"})
hl.bind("SUPER + SHIFT + Return", hl.dsp.exec_cmd("ghostty"), {})
hl.bind("SUPER + Q", hl.dsp.window.close(), {})
hl.bind("SUPER + SHIFT + Q", hl.dsp.exit(), {})
hl.bind("SUPER + SHIFT + R", hl.dsp.force_renderer_reload(), {})
hl.bind("SUPER + SHIFT + L", hl.dsp.exec_cmd("~/.config/hypr/scripts/lock.sh"), {})
hl.bind("SUPER + F", hl.dsp.window.float(), {})
hl.bind("SUPER + R", hl.dsp.exec_cmd("sh -c 'exec \"$HOME/.local/bin/cornice\" \"$@\"' cornice launcher"), {})
hl.bind("SUPER + V", hl.dsp.exec_cmd("sh -c 'exec \"$HOME/.local/bin/cornice\" \"$@\"' cornice clipboard"), {})
hl.bind("SUPER + E", hl.dsp.exec_cmd("sh -c 'exec \"$HOME/.local/bin/cornice\" \"$@\"' cornice emojis"), {})
hl.bind("SUPER + N", hl.dsp.exec_cmd("sh -c 'exec \"$HOME/.local/bin/cornice\" \"$@\"' cornice notifications"), {})
hl.bind("SUPER + SHIFT + N", hl.dsp.exec_cmd("sh -c 'exec \"$HOME/.local/bin/cornice\" \"$@\"' cornice notifications"), {})
hl.bind("SUPER + M", hl.dsp.window.fullscreen({["mode"]="maximized"}), {})
hl.bind("SUPER + SHIFT + M", hl.dsp.window.fullscreen({["mode"]="fullscreen"}), {})
hl.bind("SUPER + ALT + A", hl.dsp.exec_cmd("sh -c 'exec \"$HOME/.local/bin/cornice\" \"$@\"' cornice panel cn.audio"), {})
hl.bind("SUPER + ALT + W", hl.dsp.exec_cmd("sh -c 'exec \"$HOME/.local/bin/cornice\" \"$@\"' cornice panel cn.network"), {})
hl.bind("SUPER + ALT + B", hl.dsp.exec_cmd("sh -c 'exec \"$HOME/.local/bin/cornice\" \"$@\"' cornice panel cn.bluetooth"), {})
hl.bind("SUPER + ALT + C", hl.dsp.exec_cmd("sh -c 'exec \"$HOME/.local/bin/cornice\" \"$@\"' cornice panel cn.clock"), {})
hl.bind("SUPER + ALT + P", hl.dsp.exec_cmd("sh -c 'exec \"$HOME/.local/bin/cornice\" \"$@\"' cornice panel cn.power"), {})
hl.bind("SUPER + ALT + D", hl.dsp.exec_cmd("sh -c 'exec \"$HOME/.local/bin/cornice\" \"$@\"' cornice dnd"), {})
hl.bind("SUPER + ALT + W", hl.dsp.exec_cmd("sh -c 'exec \"$HOME/.local/bin/cornice\" \"$@\"' cornice background next"), {})
hl.bind("SUPER + ALT + T", hl.dsp.exec_cmd("sh -c 'exec \"$HOME/.local/bin/cornice\" \"$@\"' cornice theme toggle"), {})
hl.bind("SUPER + ALT + V", hl.dsp.exec_cmd("sh -c 'exec \"$HOME/.local/bin/cornice\" \"$@\"' cornice osd volume"), {})
hl.bind("SUPER + ALT + R", hl.dsp.exec_cmd("sh -c 'exec \"$HOME/.local/bin/cornice\" \"$@\"' cornice restart"), {})
hl.bind("Print", hl.dsp.exec_cmd("grim -g \"$(slurp)\" - | satty --filename -"), {})
hl.bind("SUPER + P", hl.dsp.exec_cmd("grim -g \"$(slurp)\" - | satty --filename -"), {})
hl.bind("SUPER + SHIFT + P", hl.dsp.exec_cmd("grim - | satty --filename -"), {})
hl.bind("SUPER + Return", hl.dsp.layout("swapwithmaster master"), {})
hl.bind("SUPER + j", hl.dsp.exec_cmd("~/.config/hypr/scripts/cycle-focus-fullscreen.sh next"), {})
hl.bind("SUPER + k", hl.dsp.exec_cmd("~/.config/hypr/scripts/cycle-focus-fullscreen.sh prev"), {})
hl.bind("SUPER + Y", hl.dsp.window.pin(), {})
hl.bind("SUPER + SHIFT + j", hl.dsp.layout("swapnext"), {})
hl.bind("SUPER + SHIFT + k", hl.dsp.layout("swapprev"), {})
hl.bind("SUPER + i", hl.dsp.exec_cmd("~/.config/hypr/scripts/layoutmsg-active.sh addmaster"), {})
hl.bind("SUPER + d", hl.dsp.exec_cmd("~/.config/hypr/scripts/layoutmsg-active.sh removemaster"), {})
hl.bind("SUPER + G", hl.dsp.group.toggle(), {})
hl.bind("SUPER + Tab", hl.dsp.group.next(), {})
hl.bind("SUPER + SHIFT + Tab", hl.dsp.group.prev(), {})
hl.bind("SUPER + CONTROL + G", hl.dsp.group.lock_active({["action"]="toggle"}), {})
hl.bind("SUPER + SHIFT + G", hl.dsp.group.lock({["action"]="toggle"}), {})
hl.bind("ALT + Tab", hl.dsp.focus({["last"]=true}), {})
hl.bind("SUPER + c", hl.dsp.window.center(), {})
hl.bind("SUPER + c", hl.dsp.window.resize({["x"]=1300.0,["y"]=800.0,["relative"]=false}), {})
hl.bind("SUPER + l", hl.dsp.exec_cmd("~/.config/hypr/scripts/layoutmsg-active.sh mfact +0.025"), {})
hl.bind("SUPER + h", hl.dsp.exec_cmd("~/.config/hypr/scripts/layoutmsg-active.sh mfact -0.025"), {})
hl.bind("SUPER + CONTROL + j", hl.dsp.exec_cmd("~/.config/hypr/scripts/cycle-focus-fullscreen.sh next all"), {})
hl.bind("SUPER + CONTROL + k", hl.dsp.exec_cmd("~/.config/hypr/scripts/cycle-focus-fullscreen.sh prev all"), {})
hl.bind("SUPER + SHIFT + CONTROL + j", hl.dsp.workspace.move({["monitor"]="+1"}), {})
hl.bind("SUPER + SHIFT + CONTROL + k", hl.dsp.workspace.move({["monitor"]="-1"}), {})
hl.bind("SUPER + 1", hl.dsp.focus({["workspace"]="1"}), {})
hl.bind("SUPER + 2", hl.dsp.focus({["workspace"]="2"}), {})
hl.bind("SUPER + 3", hl.dsp.focus({["workspace"]="3"}), {})
hl.bind("SUPER + 4", hl.dsp.focus({["workspace"]="4"}), {})
hl.bind("SUPER + 5", hl.dsp.focus({["workspace"]="5"}), {})
hl.bind("SUPER + 6", hl.dsp.focus({["workspace"]="6"}), {})
hl.bind("SUPER + 7", hl.dsp.focus({["workspace"]="7"}), {})
hl.bind("SUPER + 8", hl.dsp.focus({["workspace"]="8"}), {})
hl.bind("SUPER + 9", hl.dsp.focus({["workspace"]="9"}), {})
hl.bind("SUPER + 0", hl.dsp.focus({["workspace"]="10"}), {})
hl.bind("SUPER + Minus", hl.dsp.workspace.toggle_special(""), {})
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+"), {["repeating"]=true,["locked"]=true})
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), {["repeating"]=true,["locked"]=true})
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), {["locked"]=true})
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), {["locked"]=true})
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("~/.config/hypr/scripts/brightness.sh up 5"), {["repeating"]=true,["locked"]=true})
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("~/.config/hypr/scripts/brightness.sh down 5"), {["repeating"]=true,["locked"]=true})
hl.bind("SUPER + SHIFT + 1", hl.dsp.window.move({["workspace"]="1",["silent"]=false}), {})
hl.bind("SUPER + SHIFT + 2", hl.dsp.window.move({["workspace"]="2",["silent"]=false}), {})
hl.bind("SUPER + SHIFT + 3", hl.dsp.window.move({["workspace"]="3",["silent"]=false}), {})
hl.bind("SUPER + SHIFT + 4", hl.dsp.window.move({["workspace"]="4",["silent"]=false}), {})
hl.bind("SUPER + SHIFT + 5", hl.dsp.window.move({["workspace"]="5",["silent"]=false}), {})
hl.bind("SUPER + SHIFT + 6", hl.dsp.window.move({["workspace"]="6",["silent"]=false}), {})
hl.bind("SUPER + SHIFT + 7", hl.dsp.window.move({["workspace"]="7",["silent"]=false}), {})
hl.bind("SUPER + SHIFT + 8", hl.dsp.window.move({["workspace"]="8",["silent"]=false}), {})
hl.bind("SUPER + SHIFT + 9", hl.dsp.window.move({["workspace"]="9",["silent"]=false}), {})
hl.bind("SUPER + SHIFT + 0", hl.dsp.window.move({["workspace"]="10",["silent"]=false}), {})
hl.bind("SUPER + SHIFT + Minus", hl.dsp.window.move({["workspace"]="special",["silent"]=false}), {})
hl.bind("SUPER + mouse_down", hl.dsp.focus({["workspace"]="e+1"}), {})
hl.bind("SUPER + mouse_up", hl.dsp.focus({["workspace"]="e-1"}), {})
hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), {["mouse"]=true})
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), {["mouse"]=true})
hl.bind("SUPER + SHIFT + mouse:272", hl.dsp.window.resize(), {["mouse"]=true})
hl.bind("SUPER + SHIFT + R", hl.dsp.submap("resize"), {})
hl.bind("F8", hl.dsp.exec_cmd("~/.local/bin/hyprvoice press"), {})
hl.bind("F8", hl.dsp.exec_cmd("~/.local/bin/hyprvoice release"), {["release"]=true})
hl.bind("F9", hl.dsp.exec_cmd("~/.local/bin/hyprvoice command"), {})
hl.bind("F9", hl.dsp.exec_cmd("~/.local/bin/hyprvoice stop"), {["release"]=true})
hl.bind("SUPER + ALT + Return", hl.dsp.exec_cmd("~/.local/bin/hyprvoice commit"), {})
hl.bind("SUPER + ALT + O", hl.dsp.exec_cmd("~/.local/bin/hyprvoice raw"), {})
hl.bind("SUPER + ALT + Escape", hl.dsp.exec_cmd("~/.local/bin/hyprvoice cancel"), {})
hl.bind("SUPER + ALT + 1", hl.dsp.exec_cmd("~/.local/bin/hyprvoice scene raw"), {})
hl.bind("SUPER + ALT + 2", hl.dsp.exec_cmd("~/.local/bin/hyprvoice scene correct"), {})
hl.bind("SUPER + ALT + 3", hl.dsp.exec_cmd("~/.local/bin/hyprvoice scene format"), {})
hl.bind("SUPER + ALT + 4", hl.dsp.exec_cmd("~/.local/bin/hyprvoice scene translate"), {})
hl.define_submap("resize",function()
hl.bind("l", hl.dsp.window.resize({["x"]=30.0,["y"]=0.0,["relative"]=true}), {["repeating"]=true})
hl.bind("h", hl.dsp.window.resize({["x"]=-30.0,["y"]=0.0,["relative"]=true}), {["repeating"]=true})
hl.bind("k", hl.dsp.window.resize({["x"]=0.0,["y"]=-30.0,["relative"]=true}), {["repeating"]=true})
hl.bind("j", hl.dsp.window.resize({["x"]=0.0,["y"]=30.0,["relative"]=true}), {["repeating"]=true})
hl.bind("escape", hl.dsp.submap("reset"), {})
hl.bind("Return", hl.dsp.submap("reset"), {})
end)
if os.getenv("CORNICE_SESSION_TEST") ~= "1" then
hl.on("hyprland.start",function()
hl.exec_cmd(os.getenv("HOME") .. "/dotfiles/linux/desktop/hyprland/agent-session/session-start")
end)
end
