#!/usr/bin/env python

import sys
import os
import fire

from importlib.machinery import SourceFileLoader
setup = SourceFileLoader(
    'setup',
    os.environ['HOME'] + '/dotfiles/common/setup.py').load_module()


def main(need_confirm=True):
    setup.brew_install('neovim', need_confirm)
    setup.sh_install('install vim-plug',  [
        'curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    ], need_confirm)
    setup.sh_install('install config files', [
        'sh ~/dotfiles/nvim/nvim.symlink'
    ], need_confirm)


if __name__ == '__main__':
    fire.Fire(main)
