#!/usr/bin/env python

import sys
import os
import fire

from importlib.machinery import SourceFileLoader
setup = SourceFileLoader(
    'setup',
    os.environ['HOME'] + '/dotfiles/common/setup.py').load_module()


def main(need_confirm=True):
    setup.sh_install('set macos defaults', [
        'sh ~/dotfiles/macos/defaults.sh'
    ], need_confirm)
    setup.sh_install('set macos file limits', [
        'sudo cp -f ~/dotfiles/macos/limit.maxfiles.plist /Library/LaunchDaemons/',
        'sudo chown root:wheel /Library/LaunchDaemons/limit.maxfiles.plist',
        'sudo launchctl load -w /Library/LaunchDaemons/limit.maxfiles.plist'
    ], need_confirm)


if __name__ == '__main__':
    fire.Fire(main)
