INSTALL_PATH=$HOME/tools

# common
MENLO_FOR_POWERLINE_HOME=$INSTALL_PATH/Menlo-for-Powerline
XXNET_HOME=$INSTALL_PATH/xxnet
ZSH_HISTORY_SUBSTRING_SEARCH_HOME=$INSTALL_PATH/zsh-history-substring-search
SOLARIZED_HOME=$INSTALL_PATH/solarized

# macos
TERMTILE_HOME=$INSTALL_PATH/termtile
