#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=common.sh
source "$SCRIPT_DIR/common.sh"

TARGET="all"
MANIFEST="$MANIFEST_PATH_DEFAULT"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --target)
      TARGET="$2"
      shift 2
      ;;
    --manifest)
      MANIFEST="$2"
      shift 2
      ;;
    *)
      echo "Error: unknown arg '$1'" >&2
      exit 1
      ;;
  esac
done

if [[ ! -f "$MANIFEST" ]]; then
  echo "Error: manifest not found: $MANIFEST" >&2
  exit 1
fi

require_bin jq

render_file() {
  local out_file="$1"
  shift
  local agent_md_fragments=("$@")

  mkdir -p "$(dirname "$out_file")"

  local tmp
  tmp="$(mktemp)"

  printf '<!-- Generated by agent_config -->\n\n' > "$tmp"

  local first="1"
  for name in "${agent_md_fragments[@]}"; do
    rel_path="$(jq -r --arg n "$name" '.agent_md_fragments[$n] // empty' "$MANIFEST")"
    if [[ -z "$rel_path" ]]; then
      echo "Error: agent_md_fragment not defined: $name" >&2
      rm -f "$tmp"
      exit 1
    fi

    fragment_file="$ROOT_DIR/$rel_path"
    if [[ ! -f "$fragment_file" ]]; then
      echo "Error: agent_md_fragment file not found: $fragment_file" >&2
      rm -f "$tmp"
      exit 1
    fi

    if [[ "$first" != "1" ]]; then
      printf '\n\n' >> "$tmp"
    fi
    cat "$fragment_file" >> "$tmp"
    first="0"
  done

  mv "$tmp" "$out_file"
  echo "Rendered $out_file"
}

mapfile -t TARGET_LIST < <(resolve_targets "$TARGET")

for target_name in "${TARGET_LIST[@]}"; do
  agents_file_raw="$(jq -r ".targets.${target_name}.agents_file" "$MANIFEST")"
  agents_file="$(expand_path "$agents_file_raw")"

  mapfile -t selected_agent_md_fragments < <(jq -r ".profiles.${target_name}.agent_md_fragments[]" "$MANIFEST")
  if [[ "${#selected_agent_md_fragments[@]}" -eq 0 ]]; then
    echo "[skip] no agent_md_fragments configured for target: $target_name"
  else
    render_file "$agents_file" "${selected_agent_md_fragments[@]}"
  fi

  while IFS= read -r override_b64; do
    override_json="$(printf '%s' "$override_b64" | base64 -d)"
    project_path_raw="$(jq -r '.path' <<<"$override_json")"
    project_path="$(expand_path "$project_path_raw")"
    project_file="$(jq -r '.file' <<<"$override_json")"

    if [[ ! -d "$project_path" ]]; then
      echo "[skip] project path not found: $project_path"
      continue
    fi

    mapfile -t override_agent_md_fragments < <(jq -r '.agent_md_fragments[]' <<<"$override_json")
    render_file "$project_path/$project_file" "${override_agent_md_fragments[@]}"
  done < <(jq -r --arg t "$target_name" '.project_overrides[] | select(.target == $t) | @base64' "$MANIFEST")
done
