#!/usr/bin/env python

import sys
import os
import fire

from importlib.machinery import SourceFileLoader
setup = SourceFileLoader(
    'setup',
    os.environ['HOME'] + '/dotfiles/common/setup.py').load_module()


def main(need_confirm=True):
    setup.sh_install('install homebrew', [
        '/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'
    ], need_confirm, command='brew')
    setup.sh_install('install brew apps', [
        'brew bundle install --file=~/dotfiles/homebrew/Brewfile-short'
    ], need_confirm)
    setup.sh_install('update macos softwares', [
        'sudo softwareupdate -i -a'
    ], need_confirm)


if __name__ == '__main__':
    fire.Fire(main)
