run:
  # Timeout for analysis, e.g. 30s, 5m.
  # Default: 1m
  timeout: 5m
  # Include test files or not.
  # Default: true
  tests: false
linters:
  enable:
    - gocyclo
    - bodyclose
    - gosec
    - exportloopref
linters-settings:
  cyclop:
    # The maximal code complexity to report.
    # Default: 10
    max-complexity: 15
