#!/usr/bin/env python

import sys
import os
import fire

from importlib.machinery import SourceFileLoader
setup = SourceFileLoader(
    'setup',
    os.environ['HOME'] + '/dotfiles/common/setup.py').load_module()


def main(need_confirm=True):
    setup.brew_install('mysql@5.7', need_confirm)
    setup.sh_install('init mysql', [
        'brew services start mysql@5.7',
        'mysql_secure_installation'
    ], need_confirm)


if __name__ == '__main__':
    fire.Fire(main)
