#!/usr/bin/env python

import sys
import os
import fire

from importlib.machinery import SourceFileLoader
setup = SourceFileLoader(
    'setup',
    os.environ['HOME'] + '/dotfiles/common/setup.py').load_module()


def main(need_confirm=True):
    setup.brew_install('zsh', need_confirm)
    setup.sh_install('use zsh as default shell', [
        'sudo -s \'echo /usr/local/bin/zsh >> /etc/shells\' && chsh -s /usr/local/bin/zsh'
    ], need_confirm)
    setup.sh_install('install zplug', [
        'curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh| zsh'
    ], need_confirm, command='zplug')
    setup.sh_install('install config files', [
        'sh ~/dotfiles/zsh/zsh.symlink'
    ], need_confirm)


if __name__ == '__main__':
    fire.Fire(main)
