model = "gpt-5.5"
model_reasoning_effort = "high"
web_search = "live"

[features]
unified_exec = true
shell_snapshot = true
steer = true
web_search_request = true
multi_agent = true
memories = false
chronicle = false

[projects."/home/liufeng"]
trust_level = "trusted"

[projects."/home/liufeng/dotfiles"]
trust_level = "trusted"

[projects."/home/liufeng/Code/self/mobius"]
trust_level = "trusted"

[projects."/Users/liufeng"]
trust_level = "trusted"

[projects."/Users/liufeng/dotfiles"]
trust_level = "trusted"

[projects."/Users/liufeng/Documents/Codex/2026-05-10/skill"]
trust_level = "trusted"

[projects."/Users/liufeng/Documents/Codex/2026-05-10/skill-2"]
trust_level = "trusted"

[projects."/Users/liufeng/Documents/Codex/2026-05-10/hermes-agent"]
trust_level = "trusted"

[projects."/Users/liufeng/dotfiles-private"]
trust_level = "trusted"

[projects."/Users/liufeng/Documents/Codex/2026-05-10/repo-rcrai-repo"]
trust_level = "trusted"

[projects."/Users/liufeng/Documents/Codex/2026-05-10/archlinux-tiling-windown-manager-mac-mac"]
trust_level = "trusted"

[projects."/Users/liufeng/Code/rcrai/itau-demo"]
trust_level = "trusted"

[projects."/Users/liufeng/Documents/Codex/2026-05-11/computer-use"]
trust_level = "trusted"

[mcp_servers.chrome-devtools]
command = "npx"
args = [
    "-y",
    "chrome-devtools-mcp@latest",
    "--browser-url=http://127.0.0.1:9222"
]
env = {}
startup_timeout_ms = 20_000

[launchers]
chrome_remote = "~/dotfiles/scripts/start-chrome-remote"

[notice]
"hide_gpt-5.1-codex-max_migration_prompt" = true
hide_rate_limit_model_nudge = true

[marketplaces.openai-primary-runtime]
last_updated = "2026-05-10T01:14:39Z"
source_type = "local"
source = "/Users/liufeng/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."browser-use@openai-bundled"]
enabled = true

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."github@openai-curated"]
enabled = true

[memories]
generate_memories = false
use_memories = false
